/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.quizsenac.view;

import br.com.quizsenac.bens.Pergunta;
import br.com.quizsenac.bens.Resposta;
import br.com.quizsenac.bens.Usuario;
import br.com.quizsenac.bens.UsuarioResposta;
import br.com.quizsenac.socket.ClienteSocket;
import br.com.quizsenac.teste;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author ACER
 */
public class RespostaUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form RespostaUsuarioPanel
     */
    private static Resposta vermelho;
    private static Resposta azul;
    private static Resposta amarelo;
    private static Resposta verde;
    private Pergunta PERGUNTA;
    private static Usuario USUARIO;
    private static UsuarioResposta usuarioResposta;
    private BooleanProperty stop = new SimpleBooleanProperty(false);

    public RespostaUsuarioPanel(Pergunta pergunta) {
        initComponents();
        iniciaCronometro();
        labelCronometro.setHorizontalTextPosition(SwingConstants.CENTER);
        usuarioResposta = new UsuarioResposta();
        usuarioResposta.setUsuario(ClienteSocket.getUsuario());
        usuarioResposta.setPergunta(pergunta);

        List<Resposta> respostas = pergunta.getRespostas();
        labelPergunta.setText(pergunta.getPergunta());
        for (int i = 0; i < respostas.size(); i++) {
            vermelho = respostas.get(0);
            azul = respostas.get(1);
            amarelo = respostas.get(2);
            verde = respostas.get(3);
        }
        bVermelho.setText(vermelho.getResposta());
        bAzul.setText(azul.getResposta());
        bAmarelo.setText(amarelo.getResposta());
        bVerde.setText(verde.getResposta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        labelPergunta = new javax.swing.JLabel();
        bAmarelo = new javax.swing.JButton();
        bAzul = new javax.swing.JButton();
        bVerde = new javax.swing.JButton();
        bVermelho = new javax.swing.JButton();
        labelCronometro = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        labelPergunta.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelPergunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPergunta.setText("pergunta");

        bAmarelo.setBackground(new java.awt.Color(255, 255, 51));
        bAmarelo.setText("Amarelo");
        bAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAmareloActionPerformed(evt);
            }
        });

        bAzul.setBackground(new java.awt.Color(0, 0, 204));
        bAzul.setText("Azul");
        bAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAzulActionPerformed(evt);
            }
        });

        bVerde.setBackground(new java.awt.Color(51, 255, 51));
        bVerde.setText("verde");
        bVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerdeActionPerformed(evt);
            }
        });

        bVermelho.setBackground(new java.awt.Color(204, 0, 0));
        bVermelho.setForeground(new java.awt.Color(240, 240, 240));
        bVermelho.setText("Vermelho");
        bVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVermelhoActionPerformed(evt);
            }
        });

        labelCronometro.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        labelCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCronometro.setText("tempo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(labelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVermelhoActionPerformed
        verdadeira(vermelho);
     }//GEN-LAST:event_bVermelhoActionPerformed

    private void bAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAzulActionPerformed
        verdadeira(azul);
    }//GEN-LAST:event_bAzulActionPerformed

    private void bAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAmareloActionPerformed
        verdadeira(amarelo);
    }//GEN-LAST:event_bAmareloActionPerformed

    private void bVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerdeActionPerformed
        verdadeira(verde);
    }//GEN-LAST:event_bVerdeActionPerformed

    private void verdadeira(Resposta resposta) {
        usuarioResposta.setResposta(resposta);
        usuarioResposta.setTempo(Integer.valueOf(labelCronometro.getText()));

        if (resposta.getCorreta()) {
            usuarioResposta.setPontos(200);
            ClienteSocket.enviarParaAdmin(ClienteSocket.getIpservidor(), usuarioResposta);
            teste.abrirRespostaCerta();
        } else {
            usuarioResposta.setPontos(-20);
            ClienteSocket.enviarParaAdmin(ClienteSocket.getIpservidor(), usuarioResposta);
            teste.abrirRespostaErrada();
        }

    }

    private void iniciaCronometro() {
        Integer intervaloMilissegundos = 1000;
        Runnable runner = new Runnable() {
            Timer timer;

            public void run() {
                ActionListener actionListener = new ActionListener() {
                    private int contador = 30;

                    @Override
                    public void actionPerformed(ActionEvent event) {
                        if (contador == 0) {
                            // para o timer
                            timer.stop();
                            labelCronometro.setText("0");
                            teste.abrirTeladeEspera();
                        } else {
                            labelCronometro.setText(String.format("%d", contador));

                        }
                        contador--;
                    }
                };

                // executa o actionListener a cada 1000 ms
                timer = new Timer(intervaloMilissegundos, actionListener);
                timer.setInitialDelay(0);
                timer.start();
            }
        };

        EventQueue.invokeLater(runner);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAmarelo;
    private javax.swing.JButton bAzul;
    private javax.swing.JButton bVerde;
    private javax.swing.JButton bVermelho;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelCronometro;
    private javax.swing.JLabel labelPergunta;
    // End of variables declaration//GEN-END:variables
}
